[terminal.shell]
program = "wsl"
args = [
  "-d",
  "Debian",
  "--cd",
  "~"
]

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Fullscreen"

[font]
size = 18 
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[colors]
cursor = { text = "#000000", cursor = "#ffffff" }
